/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppArticle {
    }
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppNav {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface ArticleComponent {
        "description": string;
        "imageSrc": string;
        "title": string;
    }
    interface MenuComponent {
        "text": string;
        "url": string;
    }
    interface NavigateMenu {
    }
}
declare global {
    interface HTMLAppArticleElement extends Components.AppArticle, HTMLStencilElement {
    }
    var HTMLAppArticleElement: {
        prototype: HTMLAppArticleElement;
        new (): HTMLAppArticleElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLArticleComponentElement extends Components.ArticleComponent, HTMLStencilElement {
    }
    var HTMLArticleComponentElement: {
        prototype: HTMLArticleComponentElement;
        new (): HTMLArticleComponentElement;
    };
    interface HTMLMenuComponentElement extends Components.MenuComponent, HTMLStencilElement {
    }
    var HTMLMenuComponentElement: {
        prototype: HTMLMenuComponentElement;
        new (): HTMLMenuComponentElement;
    };
    interface HTMLNavigateMenuElement extends Components.NavigateMenu, HTMLStencilElement {
    }
    var HTMLNavigateMenuElement: {
        prototype: HTMLNavigateMenuElement;
        new (): HTMLNavigateMenuElement;
    };
    interface HTMLElementTagNameMap {
        "app-article": HTMLAppArticleElement;
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-nav": HTMLAppNavElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "article-component": HTMLArticleComponentElement;
        "menu-component": HTMLMenuComponentElement;
        "navigate-menu": HTMLNavigateMenuElement;
    }
}
declare namespace LocalJSX {
    interface AppArticle {
    }
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppNav {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface ArticleComponent {
        "description"?: string;
        "imageSrc"?: string;
        "title"?: string;
    }
    interface MenuComponent {
        "text"?: string;
        "url"?: string;
    }
    interface NavigateMenu {
    }
    interface IntrinsicElements {
        "app-article": AppArticle;
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-nav": AppNav;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "article-component": ArticleComponent;
        "menu-component": MenuComponent;
        "navigate-menu": NavigateMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-article": LocalJSX.AppArticle & JSXBase.HTMLAttributes<HTMLAppArticleElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "article-component": LocalJSX.ArticleComponent & JSXBase.HTMLAttributes<HTMLArticleComponentElement>;
            "menu-component": LocalJSX.MenuComponent & JSXBase.HTMLAttributes<HTMLMenuComponentElement>;
            "navigate-menu": LocalJSX.NavigateMenu & JSXBase.HTMLAttributes<HTMLNavigateMenuElement>;
        }
    }
}
